---
# Specific sshd configuration for ldap :
# Enable sssd get sshPublicKey
- name: 'Update sshd configuration : AuthorizedKeysCommand + AuthorizedKeysCommandUser (new) or AuthorizedKeysCommandRunAs (old)'
  ansible.builtin.lineinfile:
    create: false
    dest: /etc/ssh/sshd_config
    regexp: "^{{ item.regexp }}"
    line: "{{ item.line }}"
    validate: "/usr/sbin/sshd -T -f %s"
  with_items: "{{ ldap_client_ssh_authorizedkeys | default([]) }}"
  loop_control:
    label: "{{ item.line }}"
  notify:
    - Service | sssd | restart
    - Service | sshd | restart
