---
# Specific sshd configuration for ldap :
# Enable sssd get sshPublicKey
- name: 'Update sshd configuration : AuthorizedKeysCommand + AuthorizedKeysCommandUser (new) or AuthorizedKeysCommandRunAs (old)'
  ansible.builtin.lineinfile:
    create: false
    dest: /etc/ssh/sshd_config
    regexp: "^{{ item.regexp }}"
    line: "{{ item.line }}"
    validate: "/usr/sbin/sshd -T -f %s"
  with_items: "{{ ssh_AuthorizedKeys | default ([]) }}"
  loop_control:
    label: "{{ item.line }}"
  notify:
    - service | sssd | restart
    - service | sshd | restart
