---
- name: Service | sssd | restart
  ansible.builtin.service:
    name: sssd
    state: restarted
- name: Service | sshd | reload
  ansible.builtin.service:
    name: sshd
    state: reloaded
- name: Service | sshd | restart
  ansible.builtin.service:
    name: sshd
    state: restarted
- name: Service | nslcd | restart
  ansible.builtin.service:
    name: nslcd
    state: restarted
